---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-vault
    app.kubernetes.io/instance: {{ .Release.Name }}-vault
    component: server

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault-internal
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-vault
    app.kubernetes.io/instance: {{ .Release.Name }}-vault
    component: server
