# 
# Currently only works on at root domain "/", not path based like "/vault"
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-vault-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: vault.eks-demo-cluster.clusters.shastra.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-vault
            port: 
              number: 8200