apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vault-config
  namespace: {{ .Release.Namespace }}
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    cluster_name = "vault"
    storage "raft" {
      path = "/vault/data"
      node_id = "vault01"
    }
